/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoSudoku;

import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.SwingConstants;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Guillermo Veintemilla
 * Clase InterfazSolucion
 */
public class InterfazSolucion extends javax.swing.JFrame {

    Casilla[][] sudoku;
    Random numeroAzar = new Random();

    /**
     * Creates new form Interfaz
     */
    public InterfazSolucion(Casilla[][] sudoku) {
        this.sudoku = sudoku;
        initComponents();
        rellenar();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * Da los valores al jtable
     */
    public void rellenar() {
        jTable1.setModel(new MyTableModel());
        //centrar los valores de las celdas
        for (int i = 0; i < 9; i++) {
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            jTable1.getColumnModel().getColumn(i).setCellRenderer(tcr);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setResizable(false);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("SOLUCIÓN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Clase que definde el modelo de la tabla
     */
    class MyTableModel extends AbstractTableModel {

        Integer[][] data = null;

        /**
         * Constructor del modelo
         */
        public MyTableModel() {
            data = rellenarTabla();
        }

        /**
         * Metodo que rellena la tabla
         * @return data
         */
        public Integer[][] rellenarTabla() {

            int numFilas = 9;
            int numColumns = getColumnCount();
            Integer[][] data = new Integer[numFilas][numColumns];
            for (int fila = 0; fila < numFilas; fila++) {
                for (int columna = 0; columna < numColumns; columna++) {
                    data[fila][columna] = sudoku[fila][columna].getValor();
                }
            }

            return data;
        }

        /**
         * Cuenta las columnas
         *
         * @return numero de columnas
         */
        public int getColumnCount() {
            return 9;
        }

        /**
         * Cuenta las filas
         *
         * @return numero de filas
         */
        public int getRowCount() {
            return data.length;
        }

        /**
         * Metodo que devuelve el nombre de la columna
         *
         * @param col numero de la columna
         * @return nombre de la columna
         */
        public String getColumnName(int col) {
            return "";
        }

        /**
         * Metodo que devuelve los datos de la tabla
         *
         * @param row numero fila
         * @param col numero columna
         * @return datos de la tabla
         */
        public Object getValueAt(int row, int col) {
            return data[row][col];
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
